[package]
name = "merlin"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
colored = "2.0.0"
lazy_static = "1.4.0"
unicode-segmentation = "1.10.1"
ahash = "0.8.3"
fasthash = "0.4.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
