name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run example program (debug)
      run: cargo run program.me
    - name: Run example program (release)
      run: cargo run -r program.me
    - name: Clippy formatting check
      if: always()
      run: cargo check --verbose