name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: make release
    - name: Build dev
      run: make dev

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v3
    - name: Tests
      run: make test

  run:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - uses: actions/checkout@v3
    - name: Run example program (debug)
      run: cargo run -- program.me --time 1000
    - name: Run example program (release)
      run: cargo run -r program.me
      
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clippy formatting check
      run: cargo clippy --verbose --no-deps